### ISSUE TITLE
Sync storage working?

### ISSUE THREAD

**Issue by DaveKeehl** [PlasmoHQ/storage#22]
Hi, I recently converted one of my Chrome extensions (written in vanilla JS) to Plasmo and I love it!

However, I don't quite understand whether the sync storage is working or not. I've been careful to set the storage area to `sync` every time I need to read/write from/to storage (both with the `useStorage` in the popup, and with the `Storage` object in the content script), but if I load the unpacked production build on Chrome on two different machines with sync on, I don't see the same data being mirrored on the two separate Chrome instances.

Am I doing something wrong? Is it the expected behavior and I'm missing something?

**Comment by DaveKeehl** [comment]
Also another question. I took a look at the source code of the storage package to check which storage area gets used by default. Is it correct that the default storage area is `sync`?

**Comment by louisgv** [comment]
> If I load the unpacked production build on Chrome on two different machines with sync on, I don't see the same data being mirrored on the two separate Chrome instances.

This really depends on when chrome sync your google account (and when the 2nd instance decided to pull the new data). I'm not sure if you can force it to sync - would love to see if it's possible. 

If full control is desired, personally I'd just rollup a remote API with a redis store (or some cheap in-mem cache).

>  Is it correct that the default storage area is sync?

Yup!

**Comment by DaveKeehl** [comment]
Mmmh alright. I was asking that because I vaguely remember (I could be wrong though) that when my extension was previously written in vanilla JS, and I was using the Chrome API directly, I was able to see the same data from the two computers without needing to resort to any DB.

Thanks for the confirmation about the default storage area!

**Comment by DaveKeehl** [comment]
I just checked on MDN and it seems I did actually remember correctly. They say that "Items in sync storage are synced by the browser. The data is then available on all instances of the browser the user is logged into".

However, that doesn't happen in my case 🤔

**Comment by louisgv** [comment]
@DaveKeehl perhaps it sync based on extension ID? Check if each instance of your extension that they have the same CRXID: https://www.plasmo.com/blog/posts/how-to-create-a-consistent-id-for-your-chrome-extension

**Comment by DaveKeehl** [comment]
@louisgv overriding the manifest key did the trick! thanks 🙏🏻

**Comment by DaveKeehl** [comment]
@louisgv Ok I tried to use that action and I have one more question. I noticed that if I use it as follows:

```
 - name: Create .env with CRX public key
   uses: PlasmoHQ/soft-secret@v1
   with:
     secret: ${{ secrets.CRX_PUBLIC_KEY }}
     target: ".env"
```

The output `.env` file only contains the raw CRX public key, without being prefixed by `CRX_PUBLIC_KEY=`. Is this correct? Or should I use the `secret` field as follows?

```
 - name: Create .env with CRX public key
   uses: PlasmoHQ/soft-secret@v1
   with:
     secret: CRX_PUBLIC_KEY=${{ secrets.CRX_PUBLIC_KEY }}
     target: ".env"
```
